In [2]:
import numpy as np 

In [11]:
x = np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
x[1,1] = 1 
x[0,1] = 1
x[2,0] = 2 

In [14]:
x[:,1:] = 0

In [15]:
print(x)

[[0. 0.]
 [0. 0.]
 [2. 0.]]


In [12]:
np.argwhere(x == 2)

array([[2, 0]])

In [16]:
np.argwhere(x[:,1] != 0 )

array([[0],
       [1]])

In [21]:
np.argwhere(x[2,:] != 0 )

array([[0]])